mongo:
  image: mongo:latest
  ports:
    - "27017:27017"
  restart: always
mongo-express:
  image: mongo-express:latest
  links:
    - mongo
  environment:
    - ME_CONFIG_BASICAUTH_USERNAME="bongo"
    - ME_CONFIG_BASICAUTH_PASSWORD="bongo4thewin"
  ports:
    - "8081:8081"
frontend:
  build: ./DockerContainer/Frontend
  ports:
      - "8000:8000"
  restart: always
node:
  build: ./DockerContainer/Backend
  links:
    - mongo
    - mongo-express
  ports:
    - "3000:3000"
    - "8080:8080"
  restart: always
  volumes:
    - ./logoutput:/src/logoutput/
    - ./storage:/src/storage/
    - ./DockerContainer/Backend/test:/src/test/
router:
  build: ./DockerContainer/Router
  links:
    - node
    - frontend
    - mongo-express
  ports:
    - "80:80"
  restart: always
