node:
  build: ./lapica
  links:
    - mongo
    - mongo-express
  ports:
    - "3000:3000"
  restart: always
mongo:
  image: mongo:latest
  ports:
    - "27017:27017"
  restart: always
mongo-express:
  image: mongo-express:latest
  links:
    - mongo
  ports:
    - "8081:8081"
